# Generated by Django 2.2.1 on 2019-05-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expireDate', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=3)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
