# Generated by Django 2.2.1 on 2019-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='expireDate',
            field=models.DateTimeField(),
        ),
    ]
